name: Dereference OpenAPI files

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  dereference:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
      
    - name: Install swagger-cli
      run: npm install -g @apidevtools/swagger-cli

    - name: Dereference OpenAPI files
      run: |
        sudo apt update
        sudo apt install -y jq
        wget https://github.com/mikefarah/yq/releases/download/v4.13.4/yq_linux_amd64.tar.gz -O - |\
        tar xz && sudo mv yq_linux_amd64 /usr/bin/yq
        for file in $(find . -name '*.yaml'); do
          if yq e '.openapi != null' $file; then
            swagger-cli bundle $file -o "bundled_specifications/$(basename $file)"
          fi
        done
        for file in $(find . -name '*.json'); do
          if jq '.openapi != null' $file; then
            swagger-cli bundle $file -o "bundled_specifications/$(basename $file)"
          fi
        done

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Dereference OpenAPI files" -a || exit 0
        git push origin ${{ github.head_ref }}
