name: Dereference OpenAPI files

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  dereference:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
      
    - name: Install swagger-cli
      run: npm install -g @apidevtools/swagger-cli

    - name: Dereference OpenAPI files
      run: |
        sudo apt update
        sudo apt install -y jq
        wget https://github.com/mikefarah/yq/releases/download/v4.13.4/yq_linux_amd64.tar.gz -O - |\
        tar xz && sudo mv yq_linux_amd64 /usr/bin/yq
        for file in $(find . \( -name '*.yaml' -o -name '*.json' \) ! -path './bundled_specifications/*'); do
          if [[ $file == *.json ]]; then
            command="jq '.openapi != null'"
          else
            command="yq e '.openapi != null'"
          fi
          if eval $command $file; then
            dir=$(dirname $file)
            mkdir -p "bundled_specifications/$dir"
            if swagger-cli bundle $file -r -o "bundled_specifications/$file"; then
              echo "::group::Successfully dereferenced"
              echo $file
              echo "::endgroup::"
            else
              echo "::group::Failed to dereference"
              echo $file
              echo "::endgroup::"
            fi
          fi
        done


    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Dereference OpenAPI files" -a || exit 0
        git push origin ${{ github.head_ref }}
